export const ARC = [
    'Architecture',
    'City and Regional Planning',
    'Landscape Architecture',
];

export const ASC = [
    'Actuarial Science',
    'African American and African Studies',
    'Ancient History and Classics',
    'Anthropological Sciences',
    'Anthropology',
    'Arabic',
    'Art',
    'Art Management',
    'Astronomy and Astrophysics',
    'Atmospheric Sciences',
    'Biochemistry',
    'Biology',
    'Chemistry',
    'Chinese',
    'Classics',
    'Communication',
    'Comparative Studies',
    'Computer and Information Science',
    'Criminology and Criminal Justice Studies',
    'Dance',
    'Data Analytics',
    'Earth Sciences',
    'Economics',
    'English',
    'Evolution and Ecology',
    'Film Studies',
    'French',
    'Geographic Information Science',
    'Geography',
    'German',
    'Hebrew and Jewish Studies',
    'History',
    'History of Art',
    'Industrial Design',
    'Integrated Major in Mathematics and English',
    'Interior Design',
    'International Studies',
    'Islamic Studies',
    'Italian',
    'Italian Studies',
    'Japanese',
    'Journalism',
    'Korean',
    'Linguistics',
    'Mathematics',
    'Medical Anthropology',
    'Medieval and Renaissance Studies',
    'Microbiology',
    'Modern Greek',
    'Molecular Genetics',
    'Moving-Image Production',
    'Music',
    'Music (Composition)',
    'Music (Education)',
    'Music (Jazz Studies)',
    'Music (Musicology)',
    'Music (Performance - Orchestral Instruments)',
    'Music (Performance - Piano)',
    'Music (Performance - Voice)',
    'Music (Theory)',
    'Neuroscience',
    'Philosophy',
    'Philosophy, Politics and Economics',
    'Physics',
    'Political Science',
    'Portugese',
    'Psychology',
    'Religious Studies',
    'Romance Studies',
    'Russian',
    'Social Sciences Air Transportation',
    'Sociology',
    'Spanish',
    'Speech and Hearing Science',
    'Statistics',
    'Theatre',
    'Visual Communication Design',
    'Women, Gender and Sexuality Studies',
    'World Literatures',
    'World Politics',
    'Zoology',
];
export const BUS = [
    'Accounting',
    'Aviation Management',
    'Business Economics',
    'Finance',
    'Human Resources',
    'Information Systems',
    'Insurance',
    'International Business',
    'Logistics Management',
    'Marketing',
    'Operations Management',
    'Real Estate and Urban Analysis',
];

export const DEN = ['Dental Hygeine'];

export const EHE = [
    'Child and Youth Studies',
    'Consumer and Family Financial Services',
    'Education (Early Childhood)',
    'Education (Integrated Languate Arts/English)',
    'Education (Middle Childhood)',
    'Education (Science and Mathematics)',
    'Education (Special Ed)',
    'Education (Teaching English to Speakers of Other Languages)',
    'Education (Technical Education and Training)',
    'Education (World Language)',
    'Exercise Science Education',
    'Fashion and Retail Studies',
    'Human Promotion, Nutrition and Exercise Science',
    'Hospitality Management',
    'Human Development and Family Science',
    'Human Nutrition',
    'Sport Industry',
    'Sports Coaching, Recreation and Physical Education',
];
export const ENG = [
    'Aerospace Engineering',
    'Aviation',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science and Engineering',
    'Electrical and Computer Engineering',
    'Engineering Physics',
    'Environmental Engineering',
    'Food, Agricultural and Biological Engineering',
    'Industrial and Systems Engineering',
    'Material Science and Engineering',
    'Mechnical Engineering',
    'Welding Engineering',
];
export const ENR = [
    'Environment, Economy, Development and Sustainability',
    'Environmental Policy and Decision Making',
    'Environmental Science',
    'Forestry, Fisheries and Wildlife',
    'Natural Resource Management',
];

export const FAE = [
    'Agribusiness and Applied Economics',
    'Agricultural Communication',
    'Agricultural Systems Management',
    'Agriscience Education',
    'Animal Sciences',
    'Community Leadership',
    'Construction Systems Management',
    'Culinary Science',
    'Entomology',
    'Food Business Management',
    'Food Science and Technology',
    'Plant Health Management',
    'Plant Pathology',
    'Sustainable Agriculture',
    'Sustainable Plant Systems',
];

export const HRS = [
    'Health Information Management and Systems',
    'Health Sciences Program',
    'Medical Laboratory Science',
    'Occupational Therapy',
    'Physical Therapy',
    'Radiologic Sciences and Therapy',
    'Respiratory Therapy',
];

export const MED = ['Biomedical Science'];

export const NUR = ['Health and Wellness Innovation in Health Care', 'Nursing'];

export const PHR = ['Pharmaceutical Sciences'];

export const JGL = [
    'Public Management, Leadership and Policy',
    'Public Policy Analysis',
];

export const PUB = ['Public Health'];

export const SKW = ['Social Work'];
