export const MajorLookup = {
    def: [{ id: '0', text: 'Choose your major' }],
    Architecture: [
        { id: 1, text: 'Architecture' },
        { id: 2, text: 'City and Regional Planning' },
        { id: 3, text: 'Landscape Architecture' },
    ],
    ASC: [
        { id: 1, text: 'Actuarial Science' },
        { id: 2, text: 'African American and African Studies' },
        { id: 3, text: 'Ancient History and Classics' },
        { id: 4, text: 'Anthropological Sciences' },
        { id: 5, text: 'Anthropology' },
        { id: 6, text: 'Arabic' },
        { id: 7, text: 'Art' },
        { id: 8, text: 'Art Education' },
        { id: 10, text: 'Arts Management' },
        { id: 11, text: 'Astronomy and Astrophysics' },
        { id: 12, text: 'Atmospheric Sciences' },
        { id: 13, text: 'Biochemistry' },
        { id: 14, text: 'Biology' },
        { id: 15, text: 'Chemistry' },
        { id: 16, text: 'Chinese' },
        { id: 17, text: 'Classics' },
        { id: 18, text: 'Communication' },
        { id: 19, text: 'Comparative Studies' },
        { id: 20, text: 'Computer and Information Science' },
        { id: 21, text: 'Criminology and Criminal Justice Studies' },
        { id: 22, text: 'Dance' },
        { id: 23, text: 'Data Analytics' },
        { id: 24, text: 'Earth Sciences' },
        { id: 25, text: 'Economics' },
        { id: 26, text: 'English' },
        { id: 27, text: 'Evolution and Ecology' },
        { id: 28, text: 'Film Studies' },
        { id: 29, text: 'French' },
        { id: 30, text: 'Geographic Information Science' },
        { id: 31, text: 'Geography' },
        { id: 32, text: 'German' },
        { id: 33, text: 'Hebrew and Jewish Studies' },
        { id: 34, text: 'History' },
        { id: 35, text: 'History of Art' },
        { id: 36, text: 'Industrial Design' },
        { id: 37, text: 'Integrated Major in Mathematics and English' },
        { id: 38, text: 'Interior Design' },
        { id: 39, text: 'International Studies' },
        { id: 40, text: 'Islamic Studies' },
        { id: 41, text: 'Italian' },
        { id: 42, text: 'Italian Studies' },
        { id: 43, text: 'Japanese' },
        { id: 44, text: 'Journalism' },
        { id: 45, text: 'Korean' },
        { id: 46, text: 'Linguistics' },
        { id: 47, text: 'Mathematics' },
        { id: 48, text: 'Medical Anthropology' },
        { id: 49, text: 'Medieval and Renaissance Studies' },
        { id: 50, text: 'Microbiology' },
        { id: 51, text: 'Modern Greek' },
        { id: 52, text: 'Molecular Genetics' },
        { id: 53, text: 'Moving-Image Production' },
        { id: 54, text: 'Music' },
        { id: 56, text: 'Music - Composition' },
        { id: 57, text: 'Music - Education' },
        { id: 58, text: 'Music - Jazz Studies' },
        { id: 59, text: 'Music - Musicology' },
        { id: 60, text: 'Music - Performance (orchestral instruments)' },
        { id: 61, text: 'Music - Performance (piano)' },
        { id: 62, text: 'Music - Performance (voice)' },
        { id: 63, text: 'Music - Theory' },
        { id: 64, text: 'Neuroscience' },
        { id: 65, text: 'Philosophy' },
        { id: 66, text: 'Philosophy, Politics and Economics' },
        { id: 67, text: 'Physics' },
        { id: 68, text: 'Political Science' },
        { id: 69, text: 'Portuguese' },
        { id: 70, text: 'Psychology' },
        { id: 71, text: 'Religious Studies' },
        { id: 72, text: 'Romance Studies' },
        { id: 73, text: 'Russian' },
        { id: 74, text: 'Social Sciences Air Transportation' },
        { id: 75, text: 'Sociology' },
        { id: 76, text: 'Spanish' },
        { id: 77, text: 'Speech and Hearing Science' },
        { id: 78, text: 'Statistics' },
        { id: 79, text: 'Theatre' },
        { id: 80, text: 'Visual Communication Design' },
        { id: 81, text: "Women's, Gender and Sexuality Studies" },
        { id: 82, text: 'World Literatures' },
        { id: 83, text: 'World Politics' },
        { id: 84, text: 'Zoology' },
    ],

    Business: [
        { id: 1, text: 'Accounting' },
        { id: 2, text: 'Aviation Management' },
        { id: 4, text: 'Economics - Business' },
        { id: 5, text: 'Finance' },
        { id: 6, text: 'Human Resources' },
        { id: 7, text: 'Information Systems' },
        { id: 8, text: 'Insurance' },
        { id: 9, text: 'International Business' },
        { id: 10, text: 'Logistics Management' },
        { id: 11, text: 'Marketing' },
        { id: 12, text: 'Operations Management' },
        { id: 13, text: 'Real Estate and Urban Analysis' },
    ],
    Denistry: [{ id: 1, text: 'Dental Hygiene' }],
    EHE: [
        { id: 1, text: 'Child and Youth Studies' },
        { id: 2, text: 'Consumer and Family Financial Services' },
        { id: 3, text: 'Education -  Early Childhood Education' },
        {
            id: 4,
            text: 'Education - Integrated Language Arts/English Education',
        },
        { id: 5, text: 'Education - Middle Childhood Education' },
        { id: 6, text: 'Education - Science and Mathematics Education' },
        { id: 7, text: 'Education - Special Education' },
        {
            id: 8,
            text: 'Education - Teaching English to Speakers of Other Languages',
        },
        { id: 9, text: 'Education - Technical Education and Training' },
        { id: 10, text: 'Education - World Language Education' },
        { id: 11, text: 'Exercise Science Education' },
        { id: 12, text: 'Fashion and Retail Studies' },
        { id: 13, text: 'Health Promotion, Nutrition and Exercise Science' },
        { id: 14, text: 'Hospitality Management' },
        { id: 15, text: 'Human Development and Family Science' },
        { id: 16, text: 'Human Nutrition' },
        { id: 17, text: 'Sport Industry' },
        { id: 18, text: 'Sports Coaching, Recreation and Physical Education' },
    ],
    Engineering: [
        { id: 1, text: 'Aerospace Engineering' },
        { id: 2, text: 'Aviation' },
        { id: 3, text: 'Biomedical Engineering' },
        { id: 4, text: 'Chemical Engineering' },
        { id: 5, text: 'Civil Engineering' },
        { id: 6, text: 'Computer Science and Engineering' },
        { id: 7, text: 'Electrical and Computer Engineering' },
        { id: 8, text: 'Engineering Physics' },
        { id: 9, text: 'Environmental Engineering' },
        { id: 10, text: 'Food, Agricultural and Biological Engineering' },
        { id: 11, text: 'Industrial and Systems Engineering' },
        { id: 12, text: 'Materials Science and Engineering' },
        { id: 13, text: 'Mechanical Engineering' },
        { id: 14, text: 'Welding Engineering' },
    ],
    ENR: [
        { id: 2, text: 'Environment, Economy, Development and Sustainability' },
        { id: 3, text: 'Environmental Policy and Decision Making' },
        { id: 4, text: 'Environmental Science' },
        { id: 5, text: 'Forestry, Fisheries and Wildlife' },
        { id: 6, text: 'Natural Resource Management' },
    ],
    FAES: [
        { id: 1, text: 'Agribusiness and Applied Economics' },
        { id: 2, text: 'Agricultural Communication' },
        { id: 3, text: 'Agricultural Systems Management' },
        { id: 4, text: 'Agriculture, Exploring' },
        { id: 5, text: 'Agriscience Education' },
        { id: 6, text: 'Animal Sciences' },
        { id: 7, text: 'Community Leadership' },
        { id: 8, text: 'Construction Systems Management' },
        { id: 9, text: 'Culinary Science' },
        { id: 10, text: 'Entomology' },
        { id: 11, text: 'Food Business Management' },
        { id: 12, text: 'Food Science and Technology' },
        { id: 13, text: 'Plant Health Management' },
        { id: 14, text: 'Plant Pathology' },
        { id: 15, text: 'Professional Golf Management' },
        { id: 16, text: 'Sustainable Agriculture' },
        { id: 17, text: 'Sustainable Plant Systems' },
    ],
    HRS: [
        { id: 2, text: 'Health Information Management and Systems' },
        { id: 3, text: 'Health Sciences Program' },
        { id: 4, text: 'Medical Laboratory Science' },
        { id: 5, text: 'Occupational Therapy' },
        { id: 6, text: 'Physical Therapy' },
        { id: 7, text: 'Radiologic Sciences and Therapy' },
        { id: 8, text: 'Respiratory Therapy' },
    ],
    Medicine: [{ id: 1, text: 'Biomedical Sciences' }],
    Nursing: [
        { id: 1, text: 'Health and Wellness Innovation in Health Care' },
        { id: 2, text: 'Nursing' },
    ],
    Pharmacy: [{ id: 1, text: 'Pharmaceutical Sciences' }],
    PUA: [
        { id: 1, text: 'Public Management, Leadership and Policy' },
        { id: 2, text: 'Public Policy Analysis' },
    ],
    PHL: [{ id: 1, text: 'Public Health' }],
    SKW: [{ id: 1, text: 'Social Work' }],
};
