# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLiuhgfc():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_liuhgfc(self):
    # Test name: liuhgfc
    # Step # | name | target | value
    # 1 | open | /majors-and-academics/majors | 
    self.driver.get("http://undergrad.osu.edu/majors-and-academics/majors")
    # 2 | setWindowSize | 1440x874 | 
    self.driver.set_window_size(1440, 874)
    # 3 | click | css=.fa-chevron-down | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-chevron-down").click()
    # 4 | click | css=.col-sm-6:nth-child(2) > .checkbox:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-sm-6:nth-child(2) > .checkbox:nth-child(2)").click()
    # 5 | click | css=fieldset:nth-child(2) .checkbox:nth-child(2) > input | 
    self.driver.find_element(By.CSS_SELECTOR, "fieldset:nth-child(2) .checkbox:nth-child(2) > input").click()
    # 6 | click | id=ui-collapse-227 | 
    self.driver.find_element(By.ID, "ui-collapse-227").click()
    # 7 | close |  | 
    self.driver.close()
  
